from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.responses import StreamingResponse, JSONResponse
import pandas as pd
import io
from pathlib import Path

from pipeline import (
    process_supervised_dataset,
    process_unsupervised_dataset,
)


# ==========================================================
# FASTAPI APP
# ==========================================================

app = FastAPI(
    title="Automated ML Data Pipeline API",
    description=(
        "Backend API for supervised and unsupervised "
        "data preprocessing."
    ),
    version="2.0.0"
)


# ==========================================================
# HEALTH CHECK
# ==========================================================

@app.get("/")
def root():

    return {
        "status": "running",
        "service": "Automated ML Data Pipeline API",
        "version": "2.0.0",
        "modes": [
            "supervised",
            "unsupervised"
        ],
        "eda": (
            "EDA reports are generated by the "
            "Streamlit frontend as downloadable documents."
        )
    }


@app.get("/health")
def health():

    return {
        "status": "healthy"
    }


# ==========================================================
# CSV READER
# ==========================================================

async def read_csv_upload(
    file: UploadFile
):

    if not file.filename:

        raise HTTPException(
            status_code=400,
            detail="No file name supplied."
        )

    suffix = Path(
        file.filename
    ).suffix.lower()

    if suffix != ".csv":

        raise HTTPException(
            status_code=400,
            detail="Only CSV files are supported."
        )

    try:

        contents = await file.read()

        if not contents:

            raise HTTPException(
                status_code=400,
                detail="Uploaded file is empty."
            )

        df = pd.read_csv(
            io.BytesIO(contents)
        )

    except HTTPException:
        raise

    except Exception as e:

        raise HTTPException(
            status_code=400,
            detail=f"Could not read CSV: {e}"
        )

    if df.empty:

        raise HTTPException(
            status_code=400,
            detail="The uploaded dataset contains no rows."
        )

    return df


# ==========================================================
# DATASET INFORMATION
# ==========================================================

@app.post("/dataset/info")
async def dataset_info(
    file: UploadFile = File(...)
):

    df = await read_csv_upload(file)

    numerical = df.select_dtypes(
        include="number"
    ).columns.tolist()

    categorical = df.select_dtypes(
        exclude="number"
    ).columns.tolist()

    missing = (
        df.isna()
        .sum()
    )

    missing_features = (
        missing[
            missing > 0
        ]
        .sort_values(
            ascending=False
        )
        .to_dict()
    )

    return {
        "filename": file.filename,
        "rows": int(df.shape[0]),
        "columns": int(df.shape[1]),
        "features": df.columns.tolist(),
        "numerical_features": numerical,
        "categorical_features": categorical,
        "missing_features": {
            str(k): int(v)
            for k, v in missing_features.items()
        },
        "duplicate_rows": int(
            df.duplicated().sum()
        )
    }


# ==========================================================
# SUPERVISED PROCESSING
# ==========================================================

@app.post("/process/supervised")
async def process_supervised(
    file: UploadFile = File(...),
    target_col: str = Form(...),
    test_size: float = Form(0.20),
    random_state: int = Form(42)
):

    df = await read_csv_upload(file)

    if target_col not in df.columns:

        raise HTTPException(
            status_code=400,
            detail=(
                f"Target column '{target_col}' "
                "was not found in the dataset."
            )
        )

    try:

        result = process_supervised_dataset(
            df=df,
            target_col=target_col,
            test_size=test_size,
            random_state=random_state
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                "Supervised preprocessing failed: "
                f"{e}"
            )
        )

    X_train = result["X_train"]
    X_test = result["X_test"]

    return {
        "status": "success",
        "mode": "supervised",
        "task": result["task"],
        "target": target_col,

        "train_rows": int(
            X_train.shape[0]
        ),

        "test_rows": int(
            X_test.shape[0]
        ),

        "train_columns": int(
            X_train.shape[1]
        ),

        "test_columns": int(
            X_test.shape[1]
        ),

        "pipeline_info": result["info"]
    }


# ==========================================================
# UNSUPERVISED PROCESSING
# ==========================================================

@app.post("/process/unsupervised")
async def process_unsupervised(
    file: UploadFile = File(...),
    test_size: float = Form(0.20),
    random_state: int = Form(42)
):

    df = await read_csv_upload(file)

    try:

        result = process_unsupervised_dataset(
            df=df,
            test_size=test_size,
            random_state=random_state
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=(
                "Unsupervised preprocessing failed: "
                f"{e}"
            )
        )

    X_train = result["X_train"]
    X_test = result["X_test"]

    return {
        "status": "success",
        "mode": "unsupervised",

        "train_rows": int(
            X_train.shape[0]
        ),

        "test_rows": int(
            X_test.shape[0]
        ),

        "train_columns": int(
            X_train.shape[1]
        ),

        "test_columns": int(
            X_test.shape[1]
        ),

        "pipeline_info": result["info"]
    }


# ==========================================================
# DOWNLOAD PROCESSED DATASET
# ==========================================================

def dataframe_csv_response(
    df,
    filename
):

    csv_bytes = df.to_csv(
        index=False
    ).encode("utf-8")

    return StreamingResponse(
        io.BytesIO(csv_bytes),
        media_type="text/csv",
        headers={
            "Content-Disposition":
                f'attachment; filename="{filename}"'
        }
    )


@app.post("/download/supervised/train")
async def download_supervised_train(
    file: UploadFile = File(...),
    target_col: str = Form(...),
    test_size: float = Form(0.20),
    random_state: int = Form(42)
):

    df = await read_csv_upload(file)

    if target_col not in df.columns:

        raise HTTPException(
            status_code=400,
            detail=(
                f"Target column '{target_col}' "
                "was not found."
            )
        )

    try:

        result = process_supervised_dataset(
            df=df,
            target_col=target_col,
            test_size=test_size,
            random_state=random_state
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=str(e)
        )

    return dataframe_csv_response(
        result["X_train"],
        "processed_train.csv"
    )


@app.post("/download/supervised/test")
async def download_supervised_test(
    file: UploadFile = File(...),
    target_col: str = Form(...),
    test_size: float = Form(0.20),
    random_state: int = Form(42)
):

    df = await read_csv_upload(file)

    if target_col not in df.columns:

        raise HTTPException(
            status_code=400,
            detail=(
                f"Target column '{target_col}' "
                "was not found."
            )
        )

    try:

        result = process_supervised_dataset(
            df=df,
            target_col=target_col,
            test_size=test_size,
            random_state=random_state
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=str(e)
        )

    return dataframe_csv_response(
        result["X_test"],
        "processed_test.csv"
    )


@app.post("/download/unsupervised/train")
async def download_unsupervised_train(
    file: UploadFile = File(...),
    test_size: float = Form(0.20),
    random_state: int = Form(42)
):

    df = await read_csv_upload(file)

    try:

        result = process_unsupervised_dataset(
            df=df,
            test_size=test_size,
            random_state=random_state
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=str(e)
        )

    return dataframe_csv_response(
        result["X_train"],
        "processed_train.csv"
    )


@app.post("/download/unsupervised/test")
async def download_unsupervised_test(
    file: UploadFile = File(...),
    test_size: float = Form(0.20),
    random_state: int = Form(42)
):

    df = await read_csv_upload(file)

    try:

        result = process_unsupervised_dataset(
            df=df,
            test_size=test_size,
            random_state=random_state
        )

    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=str(e)
        )

    return dataframe_csv_response(
        result["X_test"],
        "processed_test.csv"
    )


# ==========================================================
# RUN LOCALLY
# ==========================================================

if __name__ == "__main__":

    import uvicorn

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000
    )
